### PR TITLE
Initial go at wagtail2

### PR DESCRIPTION
**Pull request by stuaxo**
I had a bit of a go at wagtail2.

Haven't worked out how to get testing working so no idea if this works yet.

### CODE REVIEW

**Comment by akx** [comment]
Code looks nice, but that Travis matrix failure is pretty weird indeed!

**Comment by stuaxo** [comment]
I tried so many combinations .... and couldn't work out how to do it.

Almost tempting to have an explicit entry for each combination ?

**Comment by akx** [comment]
Sure, that'll work. Not too many combinations so far anyway, so go ahead :)

**Comment by stuaxo** [comment]
The nice folks at Travis pointed out the fix - case was wrong in the exclude rule.

**Comment by stuaxo** [comment]
Hey @akx any chance of merging this ?

I've been procrastinating on my sites feature that uses wagtail-svgmap, and if this is merged I'll have no excuse..

**Comment by akx** [comment]
Looks good! I'll squash-merge these. Thank you for the work! :)

**Comment by stuaxo** [comment]
Awesome !   Right, I have no excuse now but to use this :D

Look forward to seeing it on pypi ;)

**Pull request merged**
